# Generated by Django 3.2.7 on 2021-10-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20211017_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('order_status', models.CharField(max_length=100)),
                ('payer_email', models.EmailField(max_length=254)),
                ('payer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payee_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_created_at', models.DateTimeField(blank=True, null=True)),
                ('order_updated_at', models.DateTimeField(blank=True, null=True)),
                ('pay_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency_code', models.CharField(max_length=50)),
                ('payment_created_at', models.DateTimeField(blank=True, null=True)),
                ('payment_updated_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_transaction', to='payment.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
            },
        ),
    ]
