# Generated by Django 3.2.7 on 2021-10-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_profile_user'),
        ('payment', '0006_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('NGO', 'NGO'), ('DONEE', 'Donee'), ('PLATFORM', 'Platform'), ('PGW', 'PGW')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user.profile'),
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pgw_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('ngo_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('donee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('platform_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_distribution', to='payment.transaction', verbose_name='transaction')),
            ],
            options={
                'verbose_name': 'Distribution',
                'verbose_name_plural': 'Distributions',
                'db_table': 'distributions',
            },
        ),
    ]
