# Generated by Django 3.2.7 on 2021-10-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_auto_20211019_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='DedicationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('DEDICATED', 'Dedication'), ('GIFT', 'Gift')], max_length=30)),
                ('is_dedicated', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_dedication', to='payment.payment', verbose_name='payment')),
            ],
            options={
                'verbose_name': 'Dedication Info',
                'verbose_name_plural': 'Dedication Infos',
                'db_table': 'dedication_infos',
            },
        ),
    ]
