# Generated by Django 3.2.7 on 2021-10-21 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_dedicationinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_wallet', to='payment.distribution', verbose_name='Distribution')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_distribution', to='payment.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'WalletDistribution',
                'verbose_name_plural': 'WalletDistributions',
                'db_table': 'wallet_distribution',
            },
        ),
    ]
