# Generated by Django 3.2.7 on 2021-11-17 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0048_alter_ngouser_user'),
        ('goal', '0029_alter_goal_status'),
        ('payment', '0012_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='donee_cashout_status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PENDING', 'Pending'), ('REJECTED', 'Reject'), ('PAID', 'Paid')], default='INITIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='distribution',
            name='ngo_cashout_status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PENDING', 'Pending'), ('REJECTED', 'Reject'), ('PAID', 'Paid')], default='INITIAL', max_length=30),
        ),
        migrations.CreateModel(
            name='Cashout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('remark', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accept'), ('REJECTED', 'Reject'), ('PAID', 'Paid')], default='PENDING', max_length=30)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goal_cashout', to='goal.goal')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_cashout', to='user.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_cashout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashout',
                'verbose_name_plural': 'Cashouts',
                'db_table': 'cashouts',
            },
        ),
    ]
