# Generated by Django 3.2.7 on 2021-11-18 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0013_auto_20211117_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashout',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accept'), ('REJECTED_BY_NGO', 'Reject by ngo'), ('REJECTED_BY_ADMIN', 'Reject by admin'), ('PAID', 'Paid')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='donee_cashout_status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accept'), ('REJECTED_BY_NGO', 'Reject by ngo'), ('REJECTED_BY_ADMIN', 'Reject by admin'), ('PAID', 'Paid')], default='INITIAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='ngo_cashout_status',
            field=models.CharField(choices=[('INITIAL', 'Initial'), ('PENDING', 'Pending'), ('ACCEPTED', 'Accept'), ('REJECTED_BY_NGO', 'Reject by ngo'), ('REJECTED_BY_ADMIN', 'Reject by admin'), ('PAID', 'Paid')], default='INITIAL', max_length=30),
        ),
        migrations.CreateModel(
            name='CashoutDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accept'), ('REJECTED_BY_NGO', 'Reject by ngo'), ('REJECTED_BY_ADMIN', 'Reject by admin'), ('PAID', 'Paid')], default='PENDING', max_length=30)),
                ('cashout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashout_distribution', to='payment.cashout', verbose_name='Cashout')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_cashout', to='payment.distribution', verbose_name='Distribution')),
            ],
            options={
                'verbose_name': 'CashoutDistribution',
                'verbose_name_plural': 'CashoutDistributions',
                'db_table': 'cashout_distribution',
            },
        ),
    ]
