# Generated by Django 3.2.7 on 2021-11-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_alter_cashout_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashout',
            name='admin_remark',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cashout',
            name='ngo_remark',
            field=models.TextField(null=True),
        ),
    ]
