# Generated by Django 3.2.7 on 2021-11-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_cashoutaccountinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutaccountinfo',
            name='type',
            field=models.CharField(choices=[('PAYPAL', 'Paypal')], max_length=30),
        ),
    ]
