# Generated by Django 3.2.7 on 2021-12-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_alter_cashoutaccountinfo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dedicationinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='dedicationinfo',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
