# Generated by Django 3.2.7 on 2021-11-28 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('text', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('DONEE_GOAL_CREATION', 'Donee Goal Creation')], max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_user_notification', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_user_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Notification',
                'verbose_name_plural': 'Live Notifications',
                'db_table': 'live_notifications',
            },
        ),
    ]
