# Generated by Django 3.2.7 on 2021-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_livenotification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livenotification',
            name='type',
            field=models.CharField(choices=[('DONEE_GOAL_CREATION', 'Donee Goal Creation'), ('DONEE_INVITATION_ACCEPT', 'Donee Invitation Accept'), ('DONEE_GOAL_APPROVE', 'Donee Goal Approve'), ('DONATION', 'Donation'), ('GOAL_LIKE', 'Goal Like'), ('GOAL_COMMENT', 'Goal Comment'), ('PROFILE_FOLLOW', 'Profile Follow'), ('DONEE_CASHOUT_REQUEST', 'Donee Cashout Request'), ('NGO_CASHOUT_REQUEST', 'NGO Cashout Request'), ('DONEE_CASHOUT_ACCEPT', 'Donee Cashout Accept'), ('DONEE_CASHOUT_REJECT', 'Donee Cashout Reject'), ('NGO_CASHOUT_ACCEPT', 'Donee Cashout Accept'), ('NGO_CASHOUT_REJECT', 'Donee Cashout Reject')], max_length=100),
        ),
    ]
