# Generated by Django 3.2.7 on 2021-12-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_livenotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenotification',
            name='identifier',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
