# Generated by Django 3.2.7 on 2021-09-22 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=800)),
                ('full_description', models.CharField(max_length=2000)),
                ('buying_item', models.CharField(max_length=200)),
                ('online_source_url', models.URLField(max_length=400)),
                ('unit_cost', models.FloatField()),
                ('total_unit', models.IntegerField()),
                ('pgw_amount', models.FloatField()),
                ('ngo_amount', models.FloatField()),
                ('platform_amount', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('sdgs', models.CharField(max_length=1000)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
