# Generated by Django 3.2.7 on 2021-09-22 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='total_unit',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=400)),
                ('file', models.FileField(upload_to='goals')),
                ('status', models.CharField(default='In_Queue', max_length=20)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.goal')),
            ],
        ),
    ]
