# Generated by Django 3.2.7 on 2021-10-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_auto_20210922_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'sdgs',
            },
        ),
        migrations.RemoveField(
            model_name='goal',
            name='sdgs',
        ),
    ]
