# Generated by Django 3.2.7 on 2021-10-04 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_auto_20211004_0530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdgs',
            options={'verbose_name': 'SDGS', 'verbose_name_plural': 'SDGS'},
        ),
        migrations.CreateModel(
            name='GoalSDGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goal_sdgs', to='goal.goal', verbose_name='Goal')),
                ('sdgs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sdgs_goal', to='goal.sdgs', verbose_name='SDGS')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
