# Generated by Django 3.2.7 on 2021-10-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0006_auto_20211004_0614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Goal', 'verbose_name_plural': 'Goals'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media'},
        ),
        migrations.RenameField(
            model_name='sdgs',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='media',
            name='name',
        ),
        migrations.AddField(
            model_name='goal',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='video_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sdgs',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sdgs',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sdgs',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images/thumbnail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goal',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='goal',
            name='ngo_amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='goal',
            name='pgw_amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='goal',
            name='platform_amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISH', 'Publish')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='goal',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
        migrations.AlterField(
            model_name='media',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goal.goal'),
        ),
        migrations.AlterField(
            model_name='media',
            name='status',
            field=models.CharField(choices=[('IN_QUEUE', 'In_Queue'), ('IN_PROCESSING', 'In_Processing'), ('COMPLETE', 'Complete')], max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[(1, 'Image'), (2, 'Video')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='goal',
            table='goals',
        ),
        migrations.AlterModelTable(
            name='media',
            table='media',
        ),
    ]
