# Generated by Django 3.2.7 on 2021-10-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_auto_20211004_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdgs',
            name='thumbnail',
            field=models.ImageField(upload_to='images/sdgs_thumbnail'),
        ),
    ]
