# Generated by Django 3.2.7 on 2021-10-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0010_auto_20211004_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdgs',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/sdgs_thumbnail'),
        ),
    ]
