# Generated by Django 3.2.7 on 2021-10-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0011_alter_sdgs_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='type',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='value',
        ),
        migrations.AddField(
            model_name='setting',
            name='ngo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='pgw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setting',
            name='platform',
            field=models.IntegerField(default=0),
        ),
    ]
