# Generated by Django 3.2.7 on 2021-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0012_auto_20211004_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10),
        ),
    ]
