# Generated by Django 3.2.7 on 2021-10-05 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0013_alter_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='modified_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
