# Generated by Django 3.2.7 on 2021-10-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0016_alter_media_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20),
        ),
    ]
