# Generated by Django 3.2.7 on 2021-10-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0017_alter_goal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1),
            preserve_default=False,
        ),
    ]
