# Generated by Django 3.2.7 on 2021-10-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0018_goal_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='ngo_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='goal',
            name='pgw_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='goal',
            name='platform_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
