# Generated by Django 3.2.7 on 2021-10-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0019_auto_20211011_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='ngo_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='pgw_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='platform_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
