# Generated by Django 3.2.7 on 2021-10-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0020_auto_20211011_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
