# Generated by Django 3.2.7 on 2021-10-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0021_goal_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
