# Generated by Django 3.2.7 on 2021-10-31 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_user_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goal', '0023_auto_20211027_0450'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_saved', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saved_goal', to='goal.goal')),
                ('has_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goalsave_has_profile', to='user.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goalsave_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GoalSave',
                'verbose_name_plural': 'GoalSaves',
                'db_table': 'goalsave',
            },
        ),
    ]
