# Generated by Django 3.2.7 on 2021-11-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_user_phone_number'),
        ('goal', '0024_goalsave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='has_profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_comment', to='user.profile'),
        ),
    ]
