# Generated by Django 3.2.7 on 2021-11-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0025_alter_goal_profile'),
        ('goal', '0025_auto_20211102_1345'),
    ]

    operations = [
    ]
