# Generated by Django 3.2.7 on 2021-11-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_user_total_donated_amount'),
        ('goal', '0026_merge_0025_alter_goal_profile_0025_auto_20211102_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='has_profile',
        ),
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_like', to='user.profile'),
        ),
    ]
