# Generated by Django 3.2.7 on 2021-11-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_user_total_donated_amount'),
        ('goal', '0027_auto_20211103_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalsave',
            name='has_profile',
        ),
        migrations.AddField(
            model_name='goalsave',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_goalsave', to='user.profile'),
        ),
    ]
