# Generated by Django 3.2.7 on 2021-11-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0028_auto_20211104_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
