# Generated by Django 3.2.7 on 2021-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0029_alter_goal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='online_source_url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
