# Generated by Django 3.2.7 on 2021-12-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0030_alter_goal_online_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='compressed_image',
            field=models.ImageField(null=True, upload_to='images/goal_compressed_images'),
        ),
    ]
