# Generated by Django 3.2.7 on 2021-09-21 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profiletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('goal_amount', models.FloatField(default=0)),
                ('blog_amount', models.FloatField(default=0)),
                ('extra_goal_cost', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_profile_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=50)),
                ('rut_path', models.CharField(blank=True, max_length=100, null=True)),
                ('cdc_path', models.CharField(blank=True, max_length=100, null=True)),
                ('id_front', models.CharField(blank=True, max_length=100, null=True)),
                ('id_back', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.plan')),
                ('profile_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profiletype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
