# Generated by Django 3.2.7 on 2021-09-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_plan_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
