# Generated by Django 3.2.7 on 2021-09-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210921_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cdc_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_back',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_front',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
