# Generated by Django 3.2.7 on 2021-09-29 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_types',
            new_name='profile_type',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/demo.png', upload_to='ngo_and_donee_profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ngo_profile_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.plan'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
