# Generated by Django 3.2.7 on 2021-09-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_profile_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
        migrations.AlterModelTable(
            name='profiletype',
            table='profile_types',
        ),
    ]
