# Generated by Django 3.2.7 on 2021-09-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210930_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/demo.png', upload_to='images/ngo_and_donee_profile_pictures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/demo.png', upload_to='images/user_profile_pictures'),
        ),
    ]
