# Generated by Django 3.2.7 on 2021-10-03 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210930_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('donee_notification', models.BooleanField(default=False)),
                ('account_activity', models.BooleanField(default=False)),
                ('donee_activity', models.BooleanField(default=False)),
                ('achieved_goals', models.BooleanField(default=False)),
                ('new_followers', models.BooleanField(default=False)),
                ('NGO_role_assign', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(db_column='profile', on_delete=django.db.models.deletion.PROTECT, related_name='profile_notification', to='user.profile')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.PROTECT, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
            },
        ),
    ]
