# Generated by Django 3.2.7 on 2021-10-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(db_column='profile', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile_notification', to='user.profile'),
        ),
    ]
