# Generated by Django 3.2.7 on 2021-10-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_notification_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('NGO', 'NGO'), ('DONEE', 'DONEE')], max_length=20),
        ),
    ]
