# Generated by Django 3.2.7 on 2021-10-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_profile_profile_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileType',
        ),
    ]
