# Generated by Django 3.2.7 on 2021-10-04 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_delete_profiletype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_name',
            new_name='username',
        ),
    ]
