# Generated by Django 3.2.7 on 2021-10-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0011_alter_sdgs_thumbnail'),
        ('user', '0023_auto_20211004_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSDGS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_sdgs', to='user.profile', verbose_name='Profile')),
                ('sdgs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sdgs_profile', to='goal.sdgs', verbose_name='SDGS')),
            ],
            options={
                'verbose_name': 'ProfileSDGS',
                'verbose_name_plural': 'ProfileSDGS',
                'db_table': 'profile_sdgs',
            },
        ),
    ]
