# Generated by Django 3.2.7 on 2021-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_profilesdgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(null=True),
        ),
    ]
