# Generated by Django 3.2.7 on 2021-10-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20211006_0622'),
        ('user', '0025_profile_invitation_id'),
    ]

    operations = [
    ]
