# Generated by Django 3.2.7 on 2021-11-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_donated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
