# Generated by Django 3.2.7 on 2021-11-03 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_user_total_donated_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_follow_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_follow_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_follow', models.BooleanField(default=False)),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'db_table': 'user_follow',
            },
        ),
        migrations.CreateModel(
            name='ProfileFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_follow', models.BooleanField(default=False)),
                ('follow_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_profile', to='user.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'db_table': 'profile_follow',
            },
        ),
    ]
