# Generated by Django 3.2.7 on 2021-11-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_auto_20211103_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='total_follow_count',
        ),
    ]
