# Generated by Django 3.2.7 on 2021-11-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_remove_profile_total_follow_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_follow_count',
            field=models.IntegerField(default=0),
        ),
    ]
