# Generated by Django 3.2.7 on 2021-11-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20211103_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefollow',
            old_name='is_follow',
            new_name='is_followed',
        ),
        migrations.RenameField(
            model_name='userfollow',
            old_name='is_follow',
            new_name='is_followed',
        ),
        migrations.AlterModelTable(
            name='profilefollow',
            table='profile_follow',
        ),
        migrations.AlterModelTable(
            name='userfollow',
            table='user_follow',
        ),
    ]
