# Generated by Django 3.2.7 on 2021-11-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20211107_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilefollow',
            options={'verbose_name': 'ProfileFollow', 'verbose_name_plural': 'ProfileFollows'},
        ),
        migrations.AlterModelOptions(
            name='userfollow',
            options={'verbose_name': 'UserFollow', 'verbose_name_plural': 'UserFollows'},
        ),
    ]
