# Generated by Django 3.2.7 on 2021-11-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20211110_1625'),
        ('user', '0039_profile_is_active'),
    ]

    operations = [
    ]
