# Generated by Django 3.2.7 on 2021-11-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
