# Generated by Django 3.2.7 on 2021-11-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_merge_0039_auto_20211110_1625_0039_profile_is_active'),
        ('user', '0041_alter_user_social_status'),
    ]

    operations = [
    ]
