# Generated by Django 3.2.7 on 2021-11-14 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0042_merge_20211111_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgoUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('role_type', models.CharField(choices=[('SUPERADMIN', 'SUPERADMIN'), ('ADMIN', 'ADMIN'), ('EDITOR', 'EDITOR'), ('DONEEINVITOR', 'DONEEINVITOR'), ('ACCOUNTANT', 'ACCOUNTANT')], max_length=30)),
            ],
            options={
                'verbose_name': 'NgoUserRole',
                'verbose_name_plural': 'NgoUserRoles',
                'db_table': 'ngo_user_role',
            },
        ),
        migrations.CreateModel(
            name='NgoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_profile', to='user.profile')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_ngo_user', to='user.ngouserrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NgoUser',
                'verbose_name_plural': 'NgoUsers',
                'db_table': 'ngo_user',
            },
        ),
    ]
