# Generated by Django 3.2.7 on 2021-11-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_ngouser_ngouserrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngouserrole',
            name='role_type',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('DONEEINVITOR', 'DoneeInvitor'), ('ACCOUNTANT', 'Accountant')], max_length=30),
        ),
    ]
