# Generated by Django 3.2.7 on 2021-11-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_alter_ngouser_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ngouser',
            unique_together={('user', 'profile')},
        ),
    ]
