# Generated by Django 3.2.9 on 2021-12-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_user_verification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country_code',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
