# Generated by Django 3.2.7 on 2022-01-23 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_certificationincorporation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('role_type', models.CharField(choices=[('ADMIN', 'Admin'), ('EDITOR', 'Editor'), ('DONEEINVITOR', 'DoneeInvitor'), ('ACCOUNTANT', 'Accountant')], max_length=30)),
            ],
            options={
                'verbose_name': 'Platform User Role',
                'verbose_name_plural': 'Platform User Roles',
                'db_table': 'platform_user_roles',
            },
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_platform_user', to='user.platformuserrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform User',
                'verbose_name_plural': 'Platform Users',
                'db_table': 'platform_users',
            },
        ),
    ]
